FROM golang:1.13.0-alpine3.10
CMD ["/bin/registrator"]

COPY . /go/src/github.com/gliderlabs/registrator

RUN cd /go/src/github.com/gliderlabs/registrator \
	&& GOPROXY=https://mirrors.aliyun.com/goproxy/ go build -ldflags "-X main.Version=dev" -o /bin/registrator
